#!/bin/sh
# cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation

wmake libso turbulenceModels
wmake libso incompressible
wmakeLnInclude phaseIncompressible
wmakeLnInclude phaseCompressible

#------------------------------------------------------------------------------
